#!/bin/bash

NAME="Arch Hurd Installation"
DESC="`cat description`"
MENU="Use the UP and DOWN keys to navigate the menus. Use TAB to switch between buttons and ENTER to select."
NYE="Not yet implemented."
ANSFILE="/tmp/$ANSFILE"

running=true

function partdetect()
{
    pushd /dev
    for device in hd[0-9]; do
        rm ${device}s*

        while read part; do
            echo "/dev/$part"
            MAKEDEV $part
        done < $(sfdisk -d $device | cut -d' ' -f1 | grep $device | sed 's/\/dev\///' | sed 's/p/s/')
    done
    popd
}

function welcome()
{
    dialog --title "$NAME" --msgbox "$DESC" 17 70
}

function mainmenu()
{
    dialog --title "Main Menu" --menu "$MENU" 20 45 10 \
        1 "Prepare Hard Drive(s)" \
        2 "Select Packages" \
        3 "Install Packages" \
        4 "Configure System" \
        5 "Install Bootloader" \
        6 "Exit Install" 2>$ANSFILE

    ans=`cat $ANSFILE`
    rm $ANSFILE

    case "$ans" in
        "1")      # Prepare Hard Drive(s)
            prephdds
            ;;
        "2")      # Select Packages
            choosepkg
            ;;
        "3")      # Install Packages
            installpkg
            ;;
        "4")      # Configure System
            sysconf
            ;;
        "5")      # Install Bootloader
            installgrub
            ;;
        "6" | "") # Exit Install
            yousure && exit
            ;;
    esac
}

function prephdds()
{
    sect="Prepare Hard Drive(s)"
    dialog --title "$sect" --msgbox "Ensure any /dev/hd[0-9] nodes have been created with MAKEDEV before continuing. You do not need to create the individual partition nodes (/dev/hd[0-9]s*), these will be created automatically." 7 70

    ans="1"
    while [[ "$ans" != "" ]] && [[ "$ans" != "4" ]]; do
        pas=`partdetect`

        disks=""
        parts=""

        count=1
        for device in /dev/hd[0-9]; do
            disks="$disks $count $device"
            count=$[ $count + 1 ]
        fi

        count=1
        for pa in $pas; do
            parts="$parts $count $pa"
            count=$[ $count + 1 ]
        fi

        dialog --title "$sect" --menu "$MENU" 20 45 10 \
            1 "Partition hard drives" \
            2 "Format partitions" \
            3 "Choose mount points" \
            4 "Return to Main Menu" 2>$ANSFILE

        ans=`cat $ANSFILE`
        rm $ANSFILE

        case "$ans" in
            "1") # Partition hard drives
                dialog --title "Partition hard drives" --menu "$MENU" 20 45 10 $disks 2>$ANSFILE
		ans=`cat $ANSFILE`
		rm $ANSFILE

		if [[ -e $ans ]]; then
		    yousuredata && cfdisk $ans
		fi
                ;;
            "2") # Format partitions
                dialog --title "Format partitions" --menu "$MENU" 20 45 10 $parts 2>$ANSFILE
		ans=`cat $ANSFILE`
		rm $ANSFILE

		if [[ -e $ans ]]; then
                    dialog --title "Format partitions" --menu "$MENU" 20 45 10 \
			1 "ext2" \
			2 "swap" 2>$ANSFILE
		    ans2=`cat $ANSFILE`
		    rm $ANSFILE
		    
		    case $ans2 in
			"ext2")
			    yousuredata && mkfs.ext2 $ans
			    ;;
			"swap")
			    yousuredata && mkswap $ans
			    ;;
		    esac
		fi
                ;;
            "3") # Choose mount points
                dialog --title "Choose mount points" --menu "$MENU" 20 45 10 $parts 2>$ANSFILE
		ans=`cat $ANSFILE`
		rm $ANSFILE
                ;;
        esac
    done
}

function choosepkg()
{
    dialog --title "Select Packages" --msgbox "$NYE" 5 40
}

function installpkg()
{
    dialog --title "Install Packages" --msgbox "$NYE" 5 40
}

function sysconf()
{
    dialog --title "Configure System" --msgbox "$NYE" 5 40
}

function installgrub()
{
    dialog --title "Install Bootloader" --msgbox "$NYE" 5 40
}

function yousure()
{
    dialog --title "$NAME" --yesno "Are you sure you want to exit the installation?" 6 40
}

function yousuredata()
{
    dialog --title "Warning" --yesno "This will destroy data on your HDD. Are you sure you want to continue?" 6 40
}

echo "$NAME starting..."

welcome

while true; do
    mainmenu
done